development:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_development
  pool: 5
  host: localhost
  username: postgres
  password: "postgres"

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency-test_test
  pool: 5
  host: localhost
  username: postgres
  password: "123"
